# ***introduction to pandas***

:**pandas has two divisions namely series and data frames**

# series

In [ ]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
pandas installed

In [ ]:
s = pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.values

array([10, 20, 30, 40, 50])

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
#indexing
s[2]

np.int64(30)

In [ ]:
s.name = 'clories'
s

0    1
1    2
2    3
3    4
4    5
Name: clories, dtype: int64

In [ ]:
s.iloc[3]

np.int64(40)

In [ ]:
s.name
s

0    1
1    2
2    3
3    4
4    5
Name: clories, dtype: int64

In [ ]:
index = ["apple",'banana','orange','grapes','stawberry']

In [ ]:
s.index = index
s

apple        1
banana       2
orange       3
grapes       4
stawberry    5
Name: clories, dtype: int64

In [ ]:
#loc -> lable based indexing
s.loc['apple']

np.int64(1)

In [ ]:
#In lable based indexing both the start and stop values are a must to be included in the output
s['apple':'banana']

apple     10
banana    20
Name: clories, dtype: int64

*italicized text*# ***how to use series in case of a dict.***

In [ ]:
fruit_protein = {
    'Avocado'     : 2.0, #grams of protein
    'Guava'       : 2.6,
    'blackberries': 2.0,
    'oranges'     : 0.9,
    'banana'      : 1.1,
    'apples'      : 0.3,
    'kiwi'        : 1.1,
    'pomegranate' : 1.7,
    'mangoes'     : 0.8,
    'cherries'    : 1.0
}

In [ ]:
s2 = pd.Series(fruit_protein,name = "protein")
s2

Avocado         2.0
Guava           2.6
blackberries    2.0
oranges         0.9
banana          1.1
apples          0.3
kiwi            1.1
pomegranate     1.7
mangoes         0.8
cherries        1.0
Name: protein, dtype: float64

In [ ]:
#conditional selecton
s2>1

Avocado          True
Guava            True
blackberries     True
oranges         False
banana           True
apples          False
kiwi             True
pomegranate      True
mangoes         False
cherries        False
Name: protein, dtype: bool

In [ ]:
s2[s2>1]

Avocado         2.0
Guava           2.6
blackberries    2.0
banana          1.1
kiwi            1.1
pomegranate     1.7
Name: protein, dtype: float64

In [ ]:
#logical operators: and,or,not
s2[(s2>0.5) & (s2<2)]

oranges        0.9
banana         1.1
kiwi           1.1
pomegranate    1.7
mangoes        0.8
cherries       1.0
Name: protein, dtype: float64

In [ ]:
s2[(s2>0.5) | (s2<2)]

Avocado         2.0
Guava           2.6
blackberries    2.0
oranges         0.9
banana          1.1
apples          0.3
kiwi            1.1
pomegranate     1.7
mangoes         0.8
cherries        1.0
Name: protein, dtype: float64

In [ ]:
#not operation
s2[~(s2>1)]

oranges     0.9
apples      0.3
mangoes     0.8
cherries    1.0
Name: protein, dtype: float64

In [ ]:
#modifying the series
s2['mangoe'] = 2.3

In [ ]:
s2

Avocado         2.0
Guava           2.6
blackberries    2.0
oranges         0.9
banana          1.1
apples          0.3
kiwi            1.1
pomegranate     1.7
mangoes         0.8
cherries        1.0
mangoe          2.3
Name: protein, dtype: float64

# ***data frame***

In [ ]:
import numpy as np

#data frames:

data = {
    'Name'       : ['Alice','Bob','Charlie', 'David', 'Eve', 'Alice'],
    'Age'        : [25, 30, 35, np.nan, 29, 25]                      ,
    'Department' : ['HR', 'IT', 'FINANCE', 'IT', 'HR', 'HR']              ,
    'Salary'     : [5000, 6000, 7000, 62000, np.nan, 5000]
}

In [ ]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'FINANCE', 'IT', 'HR', 'HR'],
 'Salary': [5000, 6000, 7000, 62000, nan, 5000]}

In [ ]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR   5000.0
1      Bob  30.0         IT   6000.0
2  Charlie  35.0    FINANCE   7000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR   5000.0

In [ ]:
df.head(2)

    Name   Age Department  Salary
0  Alice  25.0         HR  5000.0
1    Bob  30.0         IT  6000.0

In [ ]:
df.tail(2)

    Name   Age Department  Salary
4    Eve  29.0         HR     NaN
5  Alice  25.0         HR  5000.0

In [ ]:
#loc and iloc
df.iloc[1:3]

      Name   Age Department  Salary
1      Bob  30.0         IT  6000.0
2  Charlie  35.0    FINANCE  7000.0

In [ ]:
df.loc[1:3, ['Age','Department']]

    Age Department
1  30.0         IT
2  35.0    FINANCE
3   NaN         IT

In [ ]:
df[['Age','Department']]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    FINANCE
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [ ]:
df.drop("Age", axis = 1)

      Name Department   Salary
0    Alice         HR   5000.0
1      Bob         IT   6000.0
2  Charlie    FINANCE   7000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR   5000.0

In [ ]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR   5000.0
1      Bob  30.0         IT   6000.0
2  Charlie  35.0    FINANCE   7000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR   5000.0

In [ ]:
df.shape

(6, 4)

In [ ]:
df.dtypes

Name           object
Age           float64
Department     object
Salary        float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  17000.000000
std     4.147288  25169.425897
min    25.000000   5000.000000
25%    25.000000   5000.000000
50%    29.000000   6000.000000
75%    30.000000   7000.000000
max    35.000000  62000.000000

In [ ]:
#broadcasting

df["Salary"] = df["Salary"] + 5000

In [ ]:
df["Salary"]

0    10000.0
1    11000.0
2    12000.0
3    67000.0
4        NaN
5    10000.0
Name: Salary, dtype: float64

In [ ]:
#renaming cols

df.rename(columns = {"Department" : "Dept"}, inplace = 1) #true=1

In [ ]:
df

      Name   Age     Dept   Salary
0    Alice  25.0       HR  10000.0
1      Bob  30.0       IT  11000.0
2  Charlie  35.0  FINANCE  12000.0
3    David   NaN       IT  67000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  10000.0

In [ ]:
df['Dept'].unique()

array(['HR', 'IT', 'FINANCE'], dtype=object)

In [ ]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
FINANCE    1
Name: count, dtype: int64

In [ ]:
df['Promoted Salary'] = df["Salary"] * 10

In [ ]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  10000.0         100000.0
1      Bob  30.0       IT  11000.0         110000.0
2  Charlie  35.0  FINANCE  12000.0         120000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  10000.0         100000.0

# data **cleaning** *italicized text*

In [ ]:
# data cleaning

df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted Salary    1
dtype: int64

In [ ]:
df.dropna(how = 'any') #or df.dropna()

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  10000.0         100000.0
1      Bob  30.0       IT  11000.0         110000.0
2  Charlie  35.0  FINANCE  12000.0         120000.0
5    Alice  25.0       HR  10000.0         100000.0

In [ ]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  10000.0         100000.0
1      Bob  30.0       IT  11000.0         110000.0
2  Charlie  35.0  FINANCE  12000.0         120000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  10000.0         100000.0

In [ ]:
df.dropna(how = 'all') #any row that had any null value

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  10000.0         100000.0
1      Bob  30.0       IT  11000.0         110000.0
2  Charlie  35.0  FINANCE  12000.0         120000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  10000.0         100000.0

In [ ]:
df

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  10000.0         100000.0
1      Bob  30.0       IT  11000.0         110000.0
2  Charlie  35.0  FINANCE  12000.0         120000.0
3    David   NaN       IT  67000.0         670000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  10000.0         100000.0

In [ ]:
df.fillna(0)

      Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  10000.0         100000.0
1      Bob  30.0       IT  11000.0         110000.0
2  Charlie  35.0  FINANCE  12000.0         120000.0
3    David   0.0       IT  67000.0         670000.0
4      Eve  29.0       HR      0.0              0.0
5    Alice  25.0       HR  10000.0         100000.0

In [ ]:
df['Age'].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df["Salary"].fillna(df["Salary"].median())

0    10000.0
1    11000.0
2    12000.0
3    67000.0
4    11000.0
5    10000.0
Name: Salary, dtype: float64

In [ ]:
df["Age"].fillna(method = "ffill")#forward fill

/tmp/ipython-input-562986415.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "ffill")#forward fill

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df["Age"].fillna(method = "bfill") #backward fill

/tmp/ipython-input-1552326680.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "bfill") #backward fill

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df["Name"].replace("Charlie","Rose")

0    Alice
1      Bob
2     Rose
3    David
4      Eve
5    Alice
Name: Name, dtype: object

In [ ]:
df["Name"] = df["Name"].replace("Charlie","Rose")

In [ ]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  10000.0         100000.0
1    Bob  30.0       IT  11000.0         110000.0
2   Rose  35.0  FINANCE  12000.0         120000.0
3  David   NaN       IT  67000.0         670000.0
4    Eve  29.0       HR      NaN              NaN
5  Alice  25.0       HR  10000.0         100000.0

In [ ]:
#duplicates

df_dup = df[df.duplicated(keep = "first")]#(first give the last doop value) #out here will only return second doop value
df_dup

    Name   Age Dept   Salary  Promoted Salary
5  Alice  25.0   HR  10000.0         100000.0

In [ ]:
df_dup = df[df.duplicated(keep = "last")] #(last give the first doop value)
df_dup

    Name   Age Dept   Salary  Promoted Salary
0  Alice  25.0   HR  10000.0         100000.0

In [ ]:
df = df.drop_duplicates()

In [ ]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  10000.0         100000.0
1    Bob  30.0       IT  11000.0         110000.0
2   Rose  35.0  FINANCE  12000.0         120000.0
3  David   NaN       IT  67000.0         670000.0
4    Eve  29.0       HR      NaN              NaN

In [ ]:
#invalid values:
#lambda -> python

df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x>65000 else x)

/tmp/ipython-input-1777450787.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x>65000 else x)

In [ ]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  10000.0          10000.0
1    Bob  30.0       IT  11000.0          11000.0
2   Rose  35.0  FINANCE  12000.0          12000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  29.0       HR      NaN              NaN

In [ ]:
name = 'alice_fernandes'
df[['frist_name','last_name']] = df['Name'].str.split("_")

ValueError: Columns must be same length as key

In [ ]:
#apply and lambda
def multyply_age(x):
  return x*2

df['Age'] = df['Age'].apply( multyply_age)

/tmp/ipython-input-4181927272.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'].apply( multyply_age)

In [ ]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  50.0       HR  10000.0          10000.0
1    Bob  60.0       IT  11000.0          11000.0
2   Rose  70.0  FINANCE  12000.0          12000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  58.0       HR      NaN              NaN

In [ ]:
df["Age"] = df["Age"].apply(lambda x: x/2)

/tmp/ipython-input-1345931692.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(lambda x: x/2)

In [ ]:
df

    Name   Age     Dept   Salary  Promoted Salary
0  Alice  50.0       HR  10000.0          10000.0
1    Bob  60.0       IT  11000.0          11000.0
2   Rose  70.0  FINANCE  12000.0          12000.0
3  David   NaN       IT  67000.0          67000.0
4    Eve  58.0       HR      NaN              NaN

In [ ]:
#joins and merges
#joins -> leftjoin,rightjoin,outerjoin,innerjoin

department_info = {
    "Dept" : ["HR","IT","Finance"]                 ,
    "Location"   : ["New York","San Francisco","Chicago"],
    "Manager"    : ["Laura","Steve","Nina"]
}

df2 = pd.DataFrame(department_info)
df2

      Dept       Location Manager
0       HR       New York   Laura
1       IT  San Francisco   Steve
2  Finance        Chicago    Nina

In [ ]:
#Concat
pd.concat([df, df2]) # -> merges two dataframes

    Name   Age     Dept   Salary  Promoted Salary       Location Manager
0  Alice  25.0       HR  10000.0          10000.0            NaN     NaN
1    Bob  30.0       IT  11000.0          11000.0            NaN     NaN
2   Rose  35.0  FINANCE  12000.0          12000.0            NaN     NaN
3  David   NaN       IT  67000.0          67000.0            NaN     NaN
4    Eve  29.0       HR      NaN              NaN            NaN     NaN
0    NaN   NaN       HR      NaN              NaN       New York   Laura
1    NaN   NaN       IT      NaN              NaN  San Francisco   Steve
2    NaN   NaN  Finance      NaN              NaN        Chicago    Nina

In [ ]:
pd.concat([df, df2] , axis = 1)

,Name,Age,Dept,Salary,Promoted Salary,Dept,Location,Manager
0,Alice,25.0,HR,10000.0,10000.0,HR,New York,Laura
1,Bob,30.0,IT,11000.0,11000.0,IT,San Francisco,Steve
2,Rose,35.0,FINANCE,12000.0,12000.0,Finance,Chicago,Nina
3,David,NaN,IT,67000.0,67000.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN

In [ ]:
pd.merge(df, df2, on ="Dept")

    Name   Age Dept   Salary  Promoted Salary       Location Manager
0  Alice  25.0   HR  10000.0          10000.0       New York   Laura
1    Bob  30.0   IT  11000.0          11000.0  San Francisco   Steve
2  David   NaN   IT  67000.0          67000.0  San Francisco   Steve
3    Eve  29.0   HR      NaN              NaN       New York   Laura